'use strict';
const $=id=>document.getElementById(id);
const FIELD_IDS=['title','titleAlign','artist','summary','enMode','enTitle','enArtist','enSummary','enVenue','date','time','defaultVenue','venue','address','addressEn','detail','link','size','theme','mockup','exportFormat','marginTop','marginBottom','marginLeft','marginRight'];
const CONFIG={a2:{w:1000,h:1414.285714,mm:[420,594],px:[4961,7016],label:'A2 / 420 × 594 MM',share:.75},a4:{w:1000,h:1414.285714,mm:[210,297],px:[2480,3508],label:'A4 / 210 × 297 MM',share:.75},square:{w:1000,h:1000,mm:[285.75,285.75],px:[1080,1080],label:'WEB / 1080 × 1080 PX',share:.68},instagram:{w:1000,h:1250,mm:[285.75,357.1875],px:[1080,1350],label:'INSTAGRAM / 1080 × 1350 PX',share:.72},twitter:{w:1600,h:900,mm:[423.333333,238.125],px:[1600,900],label:'X / 1600 × 900 PX',share:.65}};
const VENUE_KO='서울시 강북구 인수봉로 301, 1F',VENUE_EN='301 Insubong-ro, Gangbuk-gu, Seoul, 1F';
const NS='http://www.w3.org/2000/svg';let translationTimer;let fonts=[],language='kr',seed=83617,current=null,downloadFile=null,downloadURL=null,translatedSource='',translationPending=false,renderTimer;
const defaults=Object.fromEntries(FIELD_IDS.map(id=>[id,$(id).type==='checkbox'?$(id).checked:$(id).value]));
function esc(t){return String(t).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));}
function setStatus(id,msg){$(id).textContent=msg;}
function source(){return {title:$('title').value,summary:$('summary').value,artist:$('artist').value,venue:$('defaultVenue').checked?'koldsleep':$('venue').value,admission:''};}
function save(){try{localStorage.setItem('textbox-poster-v2',JSON.stringify({fields:Object.fromEntries(FIELD_IDS.map(id=>[id,$(id).type==='checkbox'?$(id).checked:$(id).value])),language,seed,translatedSource}));}catch(e){}}
function restore(){try{const d=JSON.parse(localStorage.getItem('textbox-poster-v2'));if(d){for(const [k,v] of Object.entries(d.fields||{})){if(!FIELD_IDS.includes(k))continue;if($(k).type==='checkbox')$(k).checked=!!v;else $(k).value=String(v)}language=d.language==='eg'?'eg':'kr';seed=Number(d.seed)||seed;translatedSource=d.translatedSource||'';}}catch(e){}}
function showLanguage(){for(const lang of ['kr','eg']){$(lang).classList.toggle('active',language===lang);$(lang).setAttribute('aria-pressed',String(language===lang));}$('englishPanel').hidden=language!=='eg';$('customVenue').hidden=$('defaultVenue').checked;$('translate').hidden=$('enMode').value==='manual';}
function formatDate(){if(!$('date').value)return '';const [y,m,d]=$('date').value.split('-').map(Number);const day=['SUN','MON','TUE','WED','THU','FRI','SAT'][new Date(Date.UTC(y,m-1,d)).getUTCDay()];return `${y}.${String(m).padStart(2,'0')}.${String(d).padStart(2,'0')}.(${day})${$('time').value?' '+$('time').value:''}`;}
function program(){const en=language==='eg',preset=$('defaultVenue').checked;return {title:$(en?'enTitle':'title').value,artist:$(en?'enArtist':'artist').value,summary:$(en?'enSummary':'summary').value,date:formatDate(),venue:preset?(en?'koldsleep':'콜드슬립'):$(en?'enVenue':'venue').value,address:preset?(en?VENUE_EN:VENUE_KO):[en?$('addressEn').value:$('address').value,$('detail').value].filter(Boolean).join(', '),url:$('link').value.trim()};}
function randHash(s){let h=seed;for(const c of s)h=Math.imul(h^c.charCodeAt(0),16777619)>>>0;return h;}
function styled(text,context){let arr=[];let offset=0;const re=/(koldsleep|콜드슬립)/gi;for(const match of text.matchAll(re)){for(const ch of text.slice(offset,match.index))arr.push({ch,font:0});let i=0;for(const raw of match[0]){const h=randHash(context+':'+match.index+':'+i++);arr.push({ch:/[a-z]/i.test(raw)?(h%2?raw.toUpperCase():raw.toLowerCase()):raw,font:(/[a-z]/i.test(raw)?[1,5,6]:[1,2,3,4])[(h>>>2)%(/[a-z]/i.test(raw)?3:4)],random:true,source:raw});}offset=match.index+match[0].length;}for(const ch of text.slice(offset))arr.push({ch,font:0});return arr;}
function advance(g,size){const f=fonts[g.font];return f.charToGlyph(g.ch).advanceWidth/f.unitsPerEm*size;}
function width(gs,size,tracking=0){return gs.reduce((s,g)=>s+advance(g,size)+tracking,0);}
function wrap(gs,size,max,tracking=0){let lines=[],line=[],lastSpace=-1;for(const g of gs){if(g.ch==='\n'){lines.push(line);line=[];lastSpace=-1;continue;}line.push(g);if(g.ch===' ')lastSpace=line.length-1;if(width(line,size,tracking)>max&&line.length>1){if(lastSpace>0){lines.push(line.slice(0,lastSpace));line=line.slice(lastSpace+1);lastSpace=-1;}else{const last=line.pop();lines.push(line);line=[last];}}}if(line.length||!lines.length)lines.push(line);return lines;}
function scene(w,h){return {w,h,items:[],warnings:[],semantic:[],randomGlyphs:[]};}
function rect(sc,x,y,w,h,color){sc.items.push({type:'rect',x,y,w,h,color});}
function drawGlyphs(sc,gs,x,y,size,color,tracking=0){let pen=x;for(const g of gs){if(g.ch==='\n')continue;const f=fonts[g.font],path=f.getPath(g.ch,pen,y,size,{kerning:false});if(path.commands.length)sc.items.push({type:'path',commands:path.commands,color});if(g.random)sc.randomGlyphs.push({source:g.source,display:g.ch,font:g.font});pen+=advance(g,size)+tracking;}return pen;}
function textBlock(sc,text,x,y,w,{size=23,color='#000000',font=0,lineHeight=1.4,maxHeight=Infinity,minSize=size,random=true,context='body',tracking=0,align='left'}={}){if(!text)return 0;const gs=random?styled(text,context):Array.from(text,ch=>({ch,font}));let s=size,ls=wrap(gs,s,w,tracking);while(ls.length*s*lineHeight>maxHeight&&s>minSize){s-=.5;ls=wrap(gs,s,w,tracking);}if(ls.length*s*lineHeight>maxHeight+.1)sc.warnings.push(context+'의 글이 너무 깁니다. 문구를 줄여 주세요.');ls.forEach((line,i)=>{const dx=align==='right'?w-width(line,s,tracking):align==='center'?(w-width(line,s,tracking))/2:0;drawGlyphs(sc,line,x+dx,y+s+i*s*lineHeight,s,color,tracking);});sc.semantic.push(text);return ls.length*s*lineHeight;}
function titleBlock(sc,text,box,color){const gs=styled(text,'title');let s=box.w*.38,lh=1.02,ls;let words=[[]];for(const g of gs){if(/\s/.test(g.ch))words.push([]);else words[words.length-1].push(g);}const longest=Math.max(...words.map(w=>width(w,s,-s*.035)),1);if(longest>box.w*.98)s*=box.w*.98/longest;do{ls=wrap(gs,s,box.w,-s*.035);if(ls.length*s*lh<=box.h)break;s-=2;}while(s>24);if(s<=24)sc.warnings.push('타이틀이 너무 깁니다. 문구를 줄여 주세요.');sc.titleLines=ls.map(line=>line.map(g=>g.ch).join(''));const blockH=ls.length*s*lh;const y=box.y+(box.h-blockH)*.37;ls.forEach((line,i)=>{const align=$('titleAlign').value,actualWidth=width(line,s,-s*.035),dx=align==='center'?(box.w-actualWidth)/2:align==='right'?box.w-actualWidth:0;drawGlyphs(sc,line,box.x+dx,y+s+i*s*lh,s,color,-s*.035);});sc.semantic.push(text);}
function validLink(str){if(!str)return null;try{const u=new URL(str);return /^https?:$/.test(u.protocol)?u:null;}catch(e){return null;}}
function qr(sc,value,x,y,side){const q=qrcode(0,'M');q.addData(value,'Byte');q.make();const n=q.getModuleCount(),quietModules=2,cell=side/(n+2*quietModules),marginPx=quietModules*cell;rect(sc,x,y,side,side,'#ffffff');for(let r=0;r<n;r++){let start=-1;for(let c=0;c<=n;c++){const dark=c<n&&q.isDark(r,c);if(dark&&start<0)start=c;if(!dark&&start>=0){rect(sc,x+marginPx+start*cell,y+marginPx+r*cell,(c-start)*cell,cell,'#000000');start=-1;}}}sc.qr={value,modules:n,side,quietModules,quietPx:marginPx,modulePx:cell};}
function infoBlock(sc,p,b,fg,bg,{landscape=false}={}){rect(sc,b.x,b.y,b.w,b.h,bg);const web=!['a2','a4'].includes($('size').value),pad=27,x=b.x+pad,y=b.y+pad,w=b.w-pad*2,h=b.h-pad*2;const u=validLink(p.url),size=landscape?32:web?27:24;const dh=textBlock(sc,p.date,x,y,w,{size:landscape?37:web?32:34,minSize:24,maxHeight:h*.28,lineHeight:1.16,color:fg,random:false,context:'날짜'});const top=y+dh+10,avail=y+h-top,qrSide=Math.min(landscape?142:150,avail-32,w*.23),rightX=x+w-qrSide,leftW=w-qrSide-26;let cursor=top;const venue=[p.address,p.venue].filter(Boolean).join('\n');cursor+=textBlock(sc,venue,x,cursor,leftW,{size,minSize:size-2,maxHeight:avail*.68,lineHeight:1.32,color:fg,context:'장소'});if(p.artist)textBlock(sc,p.artist,x,cursor+14,leftW,{size,minSize:size-2,maxHeight:y+h-cursor-14,lineHeight:1.32,color:fg,context:'참여자'});if(u){const linkText=u.host+(u.pathname==='/'?'':u.pathname),linkSize=landscape?19:14,linkH=wrap(Array.from(linkText,ch=>({ch,font:0})),linkSize,qrSide).length*linkSize*1.25,qrY=y+h-qrSide-linkH-7;if(qrY<top)sc.warnings.push('링크가 너무 깁니다. 짧은 공개 URL을 사용해 주세요.');qr(sc,p.url,rightX,qrY,qrSide);textBlock(sc,linkText,rightX,qrY+qrSide+7,qrSide,{size:linkSize,minSize:linkSize,maxHeight:linkH,lineHeight:1.25,color:fg,random:false,context:'링크',align:'left'});}else if(p.url)sc.warnings.push('링크는 http:// 또는 https://로 입력해 주세요.');}
function posterScene(){const c=CONFIG[$('size').value],p=program(),sc=scene(c.w,c.h),dark=$('theme').value==='dark',fg=dark?'#ffffff':'#000000',bg=dark?'#000000':'#ffffff';rect(sc,0,0,c.w,c.h,bg);const m=44,iw=c.w-2*m,ih=c.h-2*m;if($('size').value==='twitter'){const titleW=iw*.65;titleBlock(sc,p.title,{x:m,y:m,w:titleW-30,h:ih-(p.summary?145:0)},fg);if(p.summary)textBlock(sc,p.summary,m,c.h-m-105,titleW-30,{size:24,minSize:22,maxHeight:105,color:fg,context:'비고'});infoBlock(sc,p,{x:m+titleW,y:m,w:iw-titleW,h:ih},bg,fg,{landscape:true});}else{const titleH=ih*c.share;titleBlock(sc,p.title,{x:m,y:m,w:iw,h:titleH-38-(p.summary?85:0)},fg);if(p.summary)textBlock(sc,p.summary,m,m+titleH-85,iw,{size:24,minSize:22,maxHeight:70,color:fg,context:'비고'});infoBlock(sc,p,{x:m,y:m+titleH,w:iw,h:ih-titleH},bg,fg);}if(language==='eg'&&!$('defaultVenue').checked&&$('address').value&&!$('addressEn').value)sc.warnings.push('영문 도로명 주소를 입력하거나 주소 검색을 이용해 주세요.');sc.program=p;return sc;}
function scaleScene(target,source,s,tx,ty){for(const item of source.items){if(item.type==='rect')target.items.push({...item,x:item.x*s+tx,y:item.y*s+ty,w:item.w*s,h:item.h*s});else target.items.push({...item,commands:item.commands.map(c=>{let n={...c};for(const k of ['x','x1','x2'])if(k in n)n[k]=n[k]*s+tx;for(const k of ['y','y1','y2'])if(k in n)n[k]=n[k]*s+ty;return n;})});}}
function mockupScene(poster){const mode=$('mockup').value;if(mode==='none')return poster;const white=mode==='wall',sc=scene(white?1600:2000,white?2000:1500);rect(sc,0,0,sc.w,sc.h,white?'#ffffff':'#000000');const top=Number($('marginTop').value)/100*sc.h,bottom=Number($('marginBottom').value)/100*sc.h,left=Number($('marginLeft').value)/100*sc.w,right=Number($('marginRight').value)/100*sc.w;const aw=sc.w-left-right,ah=sc.h-top-bottom,s=Math.min(aw/poster.w,ah/poster.h),tx=left+(aw-poster.w*s)/2,ty=top+(ah-poster.h*s)/2;scaleScene(sc,poster,s,tx,ty);sc.warnings=[...poster.warnings];sc.semantic=poster.semantic;sc.program=poster.program;sc.randomGlyphs=poster.randomGlyphs;sc.qr=poster.qr;return sc;}
function dPath(commands){return commands.map(c=>c.type==='Z'?'Z':c.type+' '+(['M','L'].includes(c.type)?`${c.x.toFixed(3)} ${c.y.toFixed(3)}`:c.type==='Q'?`${c.x1.toFixed(3)} ${c.y1.toFixed(3)} ${c.x.toFixed(3)} ${c.y.toFixed(3)}`:`${c.x1.toFixed(3)} ${c.y1.toFixed(3)} ${c.x2.toFixed(3)} ${c.y2.toFixed(3)} ${c.x.toFixed(3)} ${c.y.toFixed(3)}`)).join(' ');}
function svgString(sc,physical=false){const c=CONFIG[$('size').value],mock=$('mockup').value!=='none',print=['a2','a4'].includes($('size').value),dimension=physical&&!mock&&print?`width="${c.mm[0]}mm" height="${c.mm[1]}mm"`:`width="${mock?sc.w:c.px[0]}" height="${mock?sc.h:c.px[1]}"`;return `<svg xmlns="${NS}" ${dimension} viewBox="0 0 ${sc.w} ${sc.h}" role="img" aria-labelledby="posterTitle posterDesc"><title id="posterTitle">${esc(sc.program?.title||'Poster mockup')}</title><desc id="posterDesc">${esc(sc.semantic.join('\n'))}</desc>${sc.items.map(i=>i.type==='rect'?`<rect x="${i.x}" y="${i.y}" width="${i.w}" height="${i.h}" fill="${i.color}"/>`:`<path d="${dPath(i.commands)}" fill="${i.color}"/>`).join('')}</svg>`;}
function render(){if(!fonts.length)return;showLanguage();$('mockupMargins').hidden=$('mockup').value==='none';for(const k of ['Top','Bottom','Left','Right'])$('margin'+k+'Value').value=$('margin'+k).value+'%';current=mockupScene(posterScene());$('preview').innerHTML=svgString(current);$('preview').classList.toggle('landscape',$('size').value==='twitter');$('preview').classList.toggle('mockup',$('mockup').value!=='none');const c=CONFIG[$('size').value];$('formatLabel').textContent=c.label;$('layoutLabel').textContent=$('size').value==='twitter'?'65 : 35 / FIXED':`${Math.round(c.share*100)} : ${100-Math.round(c.share*100)} / FIXED`;$('datePreview').textContent=formatDate()||'날짜를 선택해 주세요';$('geometry').textContent=$('mockup').value==='none'?`고정 비율 ${$('layoutLabel').textContent} · 원본 지면 저장`:`목업 ${current.w} × ${current.h} px · 원본 비율 유지`;$('renderStatus').textContent=current.warnings.length?current.warnings.join(' '):'지면 준비 완료';$('qrStatus').textContent=validLink(program().url)?'QR 생성 완료 · 원본 링크를 그대로 인코딩합니다.':'http:// 또는 https:// 링크를 넣으면 QR이 생성됩니다.';$('export').disabled=current.warnings.length>0||(language==='eg'&&$('enMode').value==='auto'&&translatedSource!==JSON.stringify(source()));$('export').textContent='선택한 파일로 저장 ↗';if(language==='eg'&&$('enMode').value==='auto'&&translatedSource!==JSON.stringify(source()))setStatus('translationStatus','국문이 바뀌었습니다. 번역 / 갱신을 눌러 영문을 업데이트하세요.');save();}
function schedule(){clearTimeout(renderTimer);renderTimer=setTimeout(render,80);}
async function translate(){if(translationPending)return;translationPending=true;$('translate').disabled=true;setStatus('translationStatus','국문을 영문 프로그램 양식으로 번역하고 있습니다…');const snapshot=source(),key=JSON.stringify(snapshot),englishSnapshot=JSON.stringify(['enTitle','enSummary','enArtist','enVenue'].map(id=>$(id).value));try{const response=await fetch('https://textbox-program-translator.koldsleep.workers.dev/translate',{method:'POST',headers:{'Content-Type':'application/json'},body:key,signal:AbortSignal.timeout(60000)});const out=await response.json();if(!response.ok||!out.translation)throw Error(response.status===429?'호출이 많습니다. 1분 후 다시 시도하세요.':'번역 연결을 확인해 주세요. 직접 영문 입력도 가능합니다.');if(key!==JSON.stringify(source()))throw Error('번역 중 국문이 변경됐습니다. 원문을 확인하고 다시 번역해 주세요.');if($('enMode').value==='manual'||englishSnapshot!==JSON.stringify(['enTitle','enSummary','enArtist','enVenue'].map(id=>$(id).value))){setStatus('translationStatus','직접 입력한 영문을 유지했습니다. 자동 번역 결과는 적용하지 않았습니다.');return;}const t=out.translation;for(const [k,id] of Object.entries({title:'enTitle',summary:'enSummary',artist:'enArtist',venue:'enVenue'}))$(id).value=t[k];translatedSource=key;setStatus('translationStatus','영문 번역 완료. 고유명사·작품의 공식 표기를 확인하고 수정할 수 있습니다.');render();}catch(e){setStatus('translationStatus',e.name==='TimeoutError'?'번역 응답이 늦습니다. 다시 시도해 주세요.':e.message);}finally{translationPending=false;$('translate').disabled=false;}}
function caption(){const p=program();return [p.title.replace(/\n/g,' '),p.artist,p.summary,p.date,[p.address,p.venue].filter(Boolean).join('\n'),p.url].filter(Boolean).join('\n\n');}
function download(blob,filename){if(downloadURL)URL.revokeObjectURL(downloadURL);downloadFile=new File([blob],filename,{type:blob.type});downloadURL=URL.createObjectURL(blob);$('downloadLink').href=downloadURL;$('downloadLink').download=filename;$('downloadInfo').textContent=`${filename} · ${(blob.size/1024/1024).toFixed(2)} MB`;$('shareFile').hidden=!(navigator.canShare&&navigator.canShare({files:[downloadFile]}));$('downloadDialog').showModal();setStatus('exportStatus','파일 준비 완료. 파일 저장을 눌러 다운로드하세요.');}
function epsString(sc){const c=CONFIG[$('size').value],mock=$('mockup').value!=='none';const wp=mock?sc.w*.72:c.mm[0]*72/25.4,hp=mock?sc.h*.72:c.mm[1]*72/25.4,s=wp/sc.w;let result=[`%!PS-Adobe-3.0 EPSF-3.0`,`%%BoundingBox: 0 0 ${Math.ceil(wp)} ${Math.ceil(hp)}`,`%%HiResBoundingBox: 0 0 ${wp} ${hp}`,`%%Creator: textbox Poster Studio`,`%%LanguageLevel: 2`,`%%EndComments`,`0 ${hp} translate ${s} ${-s} scale`];for(const i of sc.items){let col=i.color.replace('#','');result.push([0,2,4].map(k=>(parseInt(col.slice(k,k+2),16)/255).toFixed(4)).join(' ')+' setrgbcolor');if(i.type==='rect'){result.push(`newpath ${i.x} ${i.y} moveto ${i.w} 0 rlineto 0 ${i.h} rlineto ${-i.w} 0 rlineto closepath fill`);}else{let px=0,py=0;result.push('newpath');for(const q of i.commands){if(q.type==='M'){result.push(`${q.x} ${q.y} moveto`);px=q.x;py=q.y;}else if(q.type==='L'){result.push(`${q.x} ${q.y} lineto`);px=q.x;py=q.y;}else if(q.type==='C'){result.push(`${q.x1} ${q.y1} ${q.x2} ${q.y2} ${q.x} ${q.y} curveto`);px=q.x;py=q.y;}else if(q.type==='Q'){result.push(`${px+2/3*(q.x1-px)} ${py+2/3*(q.y1-py)} ${q.x+2/3*(q.x1-q.x)} ${q.y+2/3*(q.y1-q.y)} ${q.x} ${q.y} curveto`);px=q.x;py=q.y;}else result.push('closepath');}result.push('fill');}}result.push('showpage','%%EOF');return result.join('\n');}

async function printJpeg(blob){const bytes=new Uint8Array(await blob.arrayBuffer());let pos=2;while(pos+18<bytes.length&&bytes[pos]===255){const marker=bytes[pos+1];if(marker===218)break;const length=(bytes[pos+2]<<8)|bytes[pos+3];if(marker===224&&String.fromCharCode(...bytes.slice(pos+4,pos+9))==='JFIF\0'){bytes[pos+11]=1;bytes[pos+12]=1;bytes[pos+13]=44;bytes[pos+14]=1;bytes[pos+15]=44;return new Blob([bytes],{type:'image/jpeg'});}if(length<2)break;pos+=2+length;}const jfif=new Uint8Array([255,224,0,16,74,70,73,70,0,1,1,1,1,44,1,44,0,0]);return new Blob([bytes.slice(0,2),jfif,bytes.slice(2)],{type:'image/jpeg'});}
async function printPng(blob){const bytes=new Uint8Array(await blob.arrayBuffer());const chunk=new Uint8Array(21);const view=new DataView(chunk.buffer);view.setUint32(0,9);chunk.set([112,72,89,115],4);view.setUint32(8,11811);view.setUint32(12,11811);chunk[16]=1;let crc=0xffffffff;for(const b of chunk.slice(4,17)){crc^=b;for(let i=0;i<8;i++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}view.setUint32(17,(crc^0xffffffff)>>>0);let pos=8;const parts=[bytes.slice(0,33),chunk];pos=33;while(pos+12<=bytes.length){const len=new DataView(bytes.buffer,bytes.byteOffset+pos,4).getUint32(0);if(pos+12+len>bytes.length)throw Error('PNG 파일을 다시 저장해 주세요.');const type=String.fromCharCode(...bytes.slice(pos+4,pos+8));if(type!=='pHYs')parts.push(bytes.slice(pos,pos+12+len));pos+=12+len;}return new Blob(parts,{type:'image/png'});}
async function exportFile(){if(!current||current.warnings.length)return;$('export').disabled=true;setStatus('exportStatus','파일을 준비하고 있습니다…');try{const sc=current,c=CONFIG[$('size').value],mock=$('mockup').value!=='none',fmt=$('exportFormat').value,filename=`textbox-${$('size').value}-${language}${mock?'-'+$('mockup').value:''}.${fmt}`;if(fmt==='svg')download(new Blob([svgString(sc,true)],{type:'image/svg+xml'}),filename);else if(fmt==='eps')download(new Blob([epsString(sc)],{type:'application/postscript'}),filename);else if(fmt==='pdf'){const dims=mock?[sc.w*.254,sc.h*.254]:c.mm;const doc=new jspdf.jsPDF({orientation:dims[0]>dims[1]?'landscape':'portrait',unit:'mm',format:dims,compress:true});const svg=new DOMParser().parseFromString(svgString(sc),'image/svg+xml').documentElement;document.body.append(svg);svg.style.position='absolute';svg.style.left='-99999px';try{await doc.svg(svg,{x:0,y:0,width:dims[0],height:dims[1]});}finally{svg.remove();}download(doc.output('blob'),filename);}else{const basePx=mock?[sc.w,sc.h]:c.px;const print=!mock&&['a2','a4'].includes($('size').value);const scale=fmt==='png'&&!print?2:1;const px=basePx.map(n=>Math.round(n*scale));const canvas=document.createElement('canvas');canvas.width=px[0];canvas.height=px[1];const ctx=canvas.getContext('2d');const url=URL.createObjectURL(new Blob([svgString(sc)],{type:'image/svg+xml'}));try{const img=new Image();img.src=url;await img.decode();ctx.drawImage(img,0,0,canvas.width,canvas.height);const blob=await new Promise(resolve=>canvas.toBlob(resolve,fmt==='png'?'image/png':'image/jpeg',.97));if(!blob)throw Error('이미지 용량을 줄여 다시 시도해 주세요.');download(print?(fmt==='png'?await printPng(blob):await printJpeg(blob)):blob,filename);}finally{URL.revokeObjectURL(url);canvas.width=canvas.height=1;}}}catch(e){setStatus('exportStatus','저장 실패: '+e.message);}finally{$('export').disabled=current.warnings.length>0||(language==='eg'&&$('enMode').value==='auto'&&translatedSource!==JSON.stringify(source()));}}
async function searchAddress(){const d=$('addressDialog');d.showModal();try{if(!window.kakao?.Postcode&&!window.daum?.Postcode){await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://t1.kakaocdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js';s.onload=resolve;s.onerror=reject;document.head.append(s);});}const Postcode=window.kakao?.Postcode||window.daum?.Postcode;new Postcode({width:'100%',height:'100%',oncomplete:data=>{$('address').value=data.roadAddress||data.address;$('addressEn').value=data.roadAddressEnglish||data.addressEnglish||'';d.close();render();$('detail').focus();}}).embed($('addressLayer'));}catch(e){d.close();setStatus('exportStatus','주소 검색 연결 실패. 주소를 직접 입력할 수 있습니다.');}}
restore();showLanguage();for(const id of FIELD_IDS)$(id).addEventListener('input',()=>{schedule();if(['title','summary','artist','venue','defaultVenue'].includes(id)&&language==='eg'&&$('enMode').value==='auto'){clearTimeout(translationTimer);translationTimer=setTimeout(translate,2200);}});for(const lang of ['kr','eg'])$(lang).onclick=()=>{language=lang;showLanguage();render();if(lang==='eg'&&$('enMode').value==='auto'&&translatedSource!==JSON.stringify(source()))translate();};$('translate').onclick=translate;$('reroll').onclick=()=>{seed=Math.floor(Math.random()*0x7fffffff);render();};$('export').onclick=exportFile;$('addressSearch').onclick=searchAddress;$('closeAddress').onclick=()=>$('addressDialog').close();$('closeDownload').onclick=()=>$('downloadDialog').close();$('shareFile').onclick=async()=>{try{await navigator.share({files:[downloadFile],title:'textbox poster'});}catch(e){if(e.name!=='AbortError')setStatus('exportStatus','공유 실패. 파일 저장 버튼을 사용하세요.');}};$('copyCaption').onclick=async()=>{try{await navigator.clipboard.writeText(caption());setStatus('translationStatus','영문 프로그램 정보를 복사했습니다.');}catch(e){setStatus('translationStatus','클립보드 접근을 허용하거나 영문 필드를 직접 복사하세요.');}};$('reset').onclick=()=>{for(const id of FIELD_IDS){if($(id).type==='checkbox')$(id).checked=defaults[id];else $(id).value=defaults[id];}language='kr';translatedSource='';render();};
Promise.all(['Pretendard-Contest.otf','Galmuri11-Contest.ttf','SongMyung-Contest.ttf','GowunBatang-Contest.ttf','NanumMyeongjo-Contest.ttf','VT323-Contest.ttf','OldStandard-Contest.ttf'].map(async filename=>{const r=await fetch('assets/'+filename);if(!r.ok)throw Error(filename+' 로드 실패');return opentype.parse(await r.arrayBuffer());})).then(result=>{fonts=result;render();}).catch(e=>{setStatus('renderStatus','폰트 로드 실패: '+e.message);setStatus('exportStatus','인터넷 또는 파일 위치를 확인하고 새로고침해 주세요.');});
// These diagnostics expose rendered values, never credentials.
window.posterDiagnostics=()=>({language,source:source(),program:program(),format:CONFIG[$('size').value],scene:current?{w:current.w,h:current.h,warnings:current.warnings,qr:current.qr,randomGlyphs:current.randomGlyphs,titleLines:current.titleLines,vectorPaths:current.items.filter(i=>i.type==='path').length}:null});

$('zoomPreview').onclick=()=>{$('zoomContent').innerHTML=svgString(current);$('zoomDialog').showModal();};$('closeZoom').onclick=()=>$('zoomDialog').close();
